export const BUCKET_SUCCESS = "BUCKET_SUCCESS";
export const BUCKET_FAILURE = "BUCKET_FAILURE";
export const BUCKET_DELETE = "BUCKET_DELETE";
export const BUCKET_CREATION = "BUCKET_CREATION";
export const BUCKET_SEARCH = "BUCKET_SEARCH";
export const BUCKET_SEARCH_CLEAR = "BUCKET_SEARCH_CLEAR";
export const BUCKET_EDIT = "BUCKET_EDIT";
